# Modelo de datos 3er entregable

# LIBRERIAS

In [1]:
import requests
import json 
import pandas as pd
import numpy as np
import datetime
'import warnings'
'warnings.filterwarnings("ignore")'

'warnings.filterwarnings("ignore")'

# Tabla driverStanding

In [2]:
driverStanding={
    'season':[],
    'round':[],
    'driverId':[],
    'points':[],
    'position':[],
    'wins':[]  
}


for year in list(range(2012,2013)):
    for i in list(range(1,24)):     
        url='http://ergast.com/api/f1/{}/{}/driverStandings.json'
        response = requests.get(url.format(year,i))
        content=json.loads(response.content)
        if content['MRData']['StandingsTable']['StandingsLists']:
            for item in content['MRData']['StandingsTable']['StandingsLists'][0]['DriverStandings']:
                try:
                    driverStanding['season'].append(year)
                except:
                    driverStanding['season'].append(np.nan)
                    
                try:
                    driverStanding['round'].append(content['MRData']['StandingsTable']['StandingsLists'][0]['round'])
                except:
                    driverStanding['round'].append(np.nan)
                    
                try:
                    driverStanding['driverId'].append(item['Driver']['driverId'])
                except:
                    driverStanding['driverId'].append(np.nan)   
         
                try:
                    driverStanding['points'].append(item['points'])
                except:
                    driverStanding['points'].append(np.nan)
                    
                try:
                    driverStanding['position'].append(item['position'])
                except:
                    driverStanding['position'].append(np.nan)
                    
                try:
                    driverStanding['wins'].append(item['wins'])
                except:
                    driverStanding['wins'].append(np.nan)

In [22]:
pd.DataFrame(driverStanding)

     season round     driverId points position wins
0      2012     1       button     25        1    1
1      2012     1       vettel     18        2    0
2      2012     1     hamilton     15        3    0
3      2012     1       webber     12        4    0
4      2012     1       alonso     10        5    0
..      ...   ...          ...    ...      ...  ...
483    2012    20          pic      0       21    0
484    2012    20   kovalainen      0       22    0
485    2012    20     ambrosio      0       23    0
486    2012    20  karthikeyan      0       24    0
487    2012    20         rosa      0       25    0

[488 rows x 6 columns]

In [3]:
pd.DataFrame(driverStanding).to_csv('driverStanding.csv', index=False)

# Tabla constructorStandings

In [4]:
constructorStanding={
    'season':[],
    'round':[],
    'constructorId':[],
    'points':[],
    'position':[],
    'wins':[]  
}


for year in list(range(2012,2013)):
    for i in list(range(1,24)):     
        url='http://ergast.com/api/f1/{}/{}/constructorStandings.json'
        response = requests.get(url.format(year,i))
        content=json.loads(response.content)
        if content['MRData']['StandingsTable']['StandingsLists']:
            for item in content['MRData']['StandingsTable']['StandingsLists'][0]['ConstructorStandings']:
                try:
                    constructorStanding['season'].append(year)
                except:
                    constructorStanding['season'].append(np.nan)
                    
                try:
                    constructorStanding['round'].append(content['MRData']['StandingsTable']['StandingsLists'][0]['round'])
                except:
                    constructorStanding['round'].append(np.nan)
                    
                try:
                    constructorStanding['constructorId'].append(item['Constructor']['constructorId'])
                except:
                    constructorStanding['constructorId'].append(np.nan)   
         
                try:
                    constructorStanding['points'].append(item['points'])
                except:
                    constructorStanding['points'].append(np.nan)
                    
                try:
                    constructorStanding['position'].append(item['position'])
                except:
                    constructorStanding['position'].append(np.nan)
                    
                try:
                    constructorStanding['wins'].append(item['wins'])
                except:
                    constructorStanding['wins'].append(np.nan)

In [25]:
pd.DataFrame(constructorStanding)

     season round constructorId points position wins
0      2012     1       mclaren     40        1    1
1      2012     1      red_bull     30        2    0
2      2012     1        sauber     12        3    0
3      2012     1       ferrari     10        4    0
4      2012     1      lotus_f1      6        5    0
..      ...   ...           ...    ...      ...  ...
234    2012    20      williams     76        8    1
235    2012    20    toro_rosso     26        9    0
236    2012    20      caterham      0       10    0
237    2012    20      marussia      0       11    0
238    2012    20           hrt      0       12    0

[239 rows x 6 columns]

In [6]:
pd.DataFrame(constructorStanding).to_csv('constructorStandings.csv',index=False)

# Tabla ConstructorResult

In [7]:
constructorResults={
        'seasons':[],
        'raceID':[],
        'points':[],
        'constructorId':[],
        'status':[]}
for year in list(range(2010,2012)):
    url='http://ergast.com/api/f1/{}/results.json'
    response = requests.get(url.format(year))
    content=json.loads(response.content)
    for year in list(range(2010,2012)):
        for i in list(range(1,len(content['MRData']['RaceTable']['Races'])+1)):
            url='http://ergast.com/api/f1/{}/{}/results.json'
            response = requests.get(url.format(year,i))
            content=json.loads(response.content)
            for item in content['MRData']['RaceTable']['Races'][0]['Results']:
                constructorResults['seasons'].append(year)
                constructorResults['raceID'].append(content['MRData']['RaceTable']['Races'][0]['raceName'])
                constructorResults['points'].append(int(item['points']))
                constructorResults['constructorId'].append(str(item['Constructor']['constructorId']))
                constructorResults['status'].append(str(item['status']))

In [28]:
pd.DataFrame(constructorResults)

     seasons                 raceID  points constructorId           status
0       2010     Bahrain Grand Prix      25       ferrari         Finished
1       2010     Bahrain Grand Prix      18       ferrari         Finished
2       2010     Bahrain Grand Prix      15       mclaren         Finished
3       2010     Bahrain Grand Prix      12      red_bull         Finished
4       2010     Bahrain Grand Prix      10      mercedes         Finished
..       ...                    ...     ...           ...              ...
139     2011  Australian Grand Prix       0      williams     Transmission
140     2011  Australian Grand Prix       0        sauber     Disqualified
141     2011  Australian Grand Prix       0        sauber     Disqualified
142     2011  Australian Grand Prix       0           hrt  Did not qualify
143     2011  Australian Grand Prix       0           hrt  Did not qualify

[144 rows x 5 columns]

In [8]:
pd.DataFrame(constructorResults).to_csv('constructorResults.csv',index=False)

# Tabla LapTimes

In [9]:
lapTimes={
    'season':[],
    'round':[],
    'raceId':[],
    'driverId':[],
    'position':[],
    'time':[],
    'lap':[]}
for year in list(range(2012,2013)):
    for i in list(range(1,3)):
        for j in list(range(1,6)):
            url='http://ergast.com/api/f1/{}/{}/laps/{}.json'
            response = requests.get(url.format(year,i,j))
            content=json.loads(response.content)
            if content['MRData']['RaceTable']['Races']:
                for item in content['MRData']['RaceTable']['Races'][0]['Laps'][0]['Timings']:
                    lapTimes['season'].append(year)
                    lapTimes['round'].append(content['MRData']['RaceTable']['Races'][0]['round'])
                    lapTimes['raceId'].append(content['MRData']['RaceTable']['Races'][0]['raceName'])
                    lapTimes['driverId'].append(item['driverId'])
                    lapTimes['lap'].append(j)
                    try:
                        lapTimes['time'].append(item['time'])
                    except:
                        lapTimes['time'].append(np.nan)
                    try:    
                        lapTimes['position'].append(item['position'])
                    except:
                        lapTimes['position'].append(np.nan)

In [31]:
pd.DataFrame(lapTimes).head(30)

,season,round,raceId,driverId,position,time,lap
0,2012,1,Australian Grand Prix,button,1,1:39.264,1
1,2012,1,Australian Grand Prix,hamilton,2,1:40.622,1
2,2012,1,Australian Grand Prix,michael_schumacher,3,1:42.002,1
3,2012,1,Australian Grand Prix,rosberg,4,1:42.666,1
4,2012,1,Australian Grand Prix,vettel,5,1:43.029,1
5,2012,1,Australian Grand Prix,grosjean,6,1:43.730,1
6,2012,1,Australian Grand Prix,maldonado,7,1:44.212,1
7,2012,1,Australian Grand Prix,alonso,8,1:44.733,1
8,2012,1,Australian Grand Prix,webber,9,1:45.336,1
9,2012,1,Australian Grand Prix,massa,10,1:46.714,1
10,2012,1,Australian Grand Prix,kobayashi,11,1:46.880,1
11,2012,1,Australian Grand Prix,perez,12,1:47.256,1
12,2012,1,Australian Grand Prix,raikkonen,13,1:48.460,1
13,2012,1,Australian Grand Prix,glock,14,1:50.819,1
14,2012,1,Australian Grand Prix,resta,15,1:50.849,1
15,2012,1,Australian Grand Prix,vergne,16,1:52.099,1
16,2012,1,Australian Grand Prix,kovalainen,17,1:53.018,1
17,2012,1,Australian Grand Prix,pic,18,1:55.732,1
18,2012,1,Australian Grand Prix,petrov,19,1:55.829,1
19,2012,1,Australian Grand Prix,bruno_senna,20,2:16.893,1
20,2012,1,Australian Grand Prix,ricciardo,21,2:37.333,1
21,2012,1,Australian Grand Prix,button,1,1:33.414,2
22,2012,1,Australian Grand Prix,hamilton,2,1:34.297,2
23,2012,1,Australian Grand Prix,michael_schumacher,3,1:35.127,2
24,2012,1,Australian Grand Prix,vettel,4,1:35.160,2
25,2012,1,Australian Grand Prix,rosberg,5,1:36.234,2
26,2012,1,Australian Grand Prix,alonso,6,1:35.866,2
27,2012,1,Australian Grand Prix,maldonado,7,1:36.857,2
28,2012,1,Australian Grand Prix,webber,8,1:35.939,2
29,2012,1,Australian Grand Prix,massa,9,1:36.908,2

In [10]:
url='http://ergast.com/api/f1/2020/5/laps/3.json'
response = requests.get(url)
content=json.loads(response.content)

In [33]:
pd.DataFrame(content['MRData']['RaceTable']['Races'][0]['Laps'][0]['Timings'])

           driverId position      time
0            bottas        1  1:31.656
1          hamilton        2  1:31.448
2    max_verstappen        3  1:31.972
3        hulkenberg        4  1:32.482
4            stroll        5  1:32.868
5         ricciardo        6  1:33.179
6             gasly        7  1:33.235
7            norris        8  1:33.862
8             albon        9  1:33.802
9           leclerc       10  1:33.930
10            sainz       11  1:34.115
11             ocon       12  1:34.245
12            kvyat       13  1:35.300
13  kevin_magnussen       14  1:36.360
14       giovinazzi       15  1:35.541
15         grosjean       16  1:35.375
16          russell       17  1:35.156
17        raikkonen       18  1:35.089
18           vettel       19  1:35.024
19           latifi       20  1:34.869

In [11]:
pd.DataFrame(lapTimes).to_csv('lapTimes.csv',index=False)